CREATE TABLE cliente (
	id uuid,
	nome CHARACTER VARYING NOT NULL,
	email CHARACTER VARYING NOT NULL UNIQUE,
	senha CHARACTER VARYING NOT NULL,
	cep CHARACTER VARYING NOT NULL,
	cidade CHARACTER VARYING NOT NULL,
	logradouro CHARACTER VARYING NOT NULL,
	bairro CHARACTER VARYING NOT NULL,
	uf CHARACTER VARYING NOT null,

	CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (id)
);